### ISSUE TITLE
How to use SafeArgs with this solution

### ISSUE THREAD

**Issue by jakoss** [ValeryPonomarenko/modular-navigation#2]
Your solution seems great, but it there a way to use SafeArgs with it? Generated classes are in app module, so feature module can't access them. And if they can't access them - they cannot use `navArgs()` function to handle incoming arguments

**Comment by ValeryPonomarenko** [comment]
I think there is no way to use SafeArgs.
But you can create a data class that will hold all the data you need and then put an object of this class inside a bundle.
Example: [createBundle ](https://github.com/ValeryPonomarenko/modular-navigation/blob/master/question/src/main/java/me/vponomarenko/modular/navigation/question/QuestionFragment.kt#L23) method and [it is used](https://github.com/ValeryPonomarenko/modular-navigation/blob/master/app/src/main/java/me/vponomarenko/modular/navigation/Navigator.kt#L51).
